Fix image cropping for jQuery v3
humanmade/smart-media pull request #121
Opened 2021-01-20 14:40 UTC by roborourke

jQuery v3 is part of WP 5.6 and now `innerHeight()` reports sub-pixel values. This throws off some of the logic in the imgareaselect jQuery plugin causing `NaN` values to be calculated for the selection area. This patches 2 things:

- `removeAttr()` no longer works for boolean attributes
- force the image width and height to the rounded values to match what imgareaselect expects

Fixes #119

2021-01-20 18:59 UTC, jazzsequence commented
I'm still having weird issues with cropping. It appears that, on some screens, like within the Media Library, I'm able to crop normally, but not on others, like in the modal within posts. Also, the UX to select a specific thumbnail is weird and doesn't seem to switch to the selected thumbnail -- this might be a separate issue.

https://www.dropbox.com/s/p1v2jn0lrlp0fyq/smart-media-crop.mov?dl=0

2021-01-20 19:01 UTC, jazzsequence requested changes
Not sure this fixes the issue entirely. See linked video.

2021-01-20 19:21 UTC, roborourke commented
Can you confirm you definitely have the updated version and run the build again? Would be good if you can send me that first image too. There could be a situation where the image size logic would only fail with some images and not others so that could explain what's happening here.

1. No crop anchors appear on an image that's attempting to be cropped - could be down to not having rebuilt files, at least I hope so! Not sure what else right now.
1. Anchors appear, but do nothing - could be due to original image upload size and not being able to cropped any smaller for the given image size
1. Anchors appear, crop can be made, but the cropped version is not inserted - this is because you had `post-thumbnail` size selected, you can only insert the sizes that the WP editor is actually aware of I think eg. thumbnail, medium or large. Check again with those but we should either try and add support for those or hide them as options within the post edit context

2021-01-20 20:30 UTC, jazzsequence commented
Okay, the UX is still weird, particularly with image sizes that _can't_ be cropped because of their size, but the actual Issue I had was that I built the files but hadn't re-symlinked smart-media locally, so it wasn't using it. 

It does seem to be working now, updating my review 👍

2021-01-20 20:30 UTC, jazzsequence approved these changes

2021-01-20 20:38 UTC, roborourke commented
I totally agree by the way - it’s not ideal and really a quirk of how the image blocks work! Really need to work on restricting the sizes you can pick in certain contexts.

2021-01-20 20:41 UTC, roborourke commented
Can you attach the images you were testing with? I’d like to double check now. Appreciate the thorough review 👍

2021-01-20 20:49 UTC, jazzsequence commented
Sure can.

![IMG_6516](https://user-images.githubusercontent.com/991511/105232763-18546100-5b26-11eb-9bce-e0e74d7ab80e.jpg)
![IMG_6510](https://user-images.githubusercontent.com/991511/105232781-20ac9c00-5b26-11eb-9381-e6a2fe24e42c.jpg)
![dnd-setup](https://user-images.githubusercontent.com/991511/105232832-328e3f00-5b26-11eb-96cd-41cb57d957b0.jpg)

2021-01-21 13:06 UTC, roborourke commented
Ok yeah so it's definitely down to some defined image sizes being larger than the original and thus you can't actually crop it any smaller. I'll add issues to handle those UX updates separately and get this fix released in the meantime.

2021-01-21 13:06 UTC, merged